### ISSUE TITLE
Cannot Resolve Method

### ISSUE THREAD

**Issue by rodrigordgfs** [Sumeet21/LoadingView#2]
Can you help me?

<a href="https://imgur.com/pX8u6yR"><img src="https://i.imgur.com/pX8u6yR.png" title="source: imgur.com" /></a>

**Comment by samigehi** [comment]
@rodrigordgfs , actually this library was written in Kotlin and you are calling it in Java code

**in Java**
 ` LoadingDialog.Companion.get(context).show()`

**in Kotlin**
 ` LoadingDialog.get(context).show()`

**Comment by rodrigordgfs** [comment]
Ok, thanks!
