### ISSUE TITLE
Error gradle sync

### ISSUE THREAD

**Issue by lendra85** [Sumeet21/LoadingView#4]
Hi,

I can not sync even using the 1.0 version.

ERROR: Failed to resolve: com.github.samigehi:loadingView:1.1

Thanks

**Comment by capps99** [comment]
same error

**Comment by samigehi** [comment]
currently v1.1 is not yet published with maven

Download and add manually **aar** file
ref
 [https://bintray.com/sumeet21/maven/com.samigehi.loadingView](https://bintray.com/sumeet21/maven/com.samigehi.loadingView)


[download](https://bintray.com/sumeet21/maven/download_file?file_path=com%2Fsamigehi%2Floadingview%2F1.1%2Floadingview-1.1.aar)

**Comment by samigehi** [comment]
use

`implementation 'com.samigehi:loadingview:1.1'`

**Comment by MenaRaafat** [comment]
implementation 'com.samigehi:loadingview:1.1' 
not working!
Android resource linking failed
